### ISSUE TITLE
Modify the readreview

### ISSUE THREAD

**Issue by RavinduSachintha** [SKYSYS-2018/ReviewsAnalysisSystem#20]
- Stars according to score
- Category in words according to category_id

**Comment by Sacheerc** [comment]
Please explain little bit about what do you mean by score? where is it located?

**Comment by RavinduSachintha** [comment]
check the controllers for each tabs.. there have passed $reviews into the view. in that array have score variable. it will currently display on each review, left side under the review content.

**Comment by Sacheerc** [comment]
Done
